import { z } from "zod";

// Zod schema for individual question validation
const questionSchema = z.object({
  question: z.string().min(3, "Question text must be at least 3 characters long"),
  options: z.array(z.string().min(1, "Option text cannot be empty")).length(4, "Options array must contain exactly 4 options"),
  correctAnswer: z.number().int().min(0).max(3, "Correct answer index must be between 0 and 3"),
  explanation: z.string().optional().default("No explanation provided."),
  points: z.number().int().positive().optional().default(10),
  topic: z.string().optional().default("General"),
  skill: z.string().optional().default("General"),
  difficulty: z.string().optional().default("medium"),
  questionType: z.string().optional().default("MCQ"),
});

// Zod schema for the entire generated assessment
const assessmentSchema = z.object({
  title: z.string().min(3, "Assessment title must be at least 3 characters long"),
  description: z.string().optional().default("Generated by AI Placement Assistant"),
  duration: z.number().int().positive().default(30),
  questions: z.array(questionSchema).min(1, "Generated assessment must contain at least 1 question"),
});

/**
 * Validates the parsed assessment structure using Zod.
 * Returns the normalized validated object or throws detailed errors.
 */
export const validateGeneratedAssessment = (data) => {
  const result = assessmentSchema.safeParse(data);
  if (!result.success) {
    const errorMsg = result.error.errors.map(err => `${err.path.join('.')}: ${err.message}`).join("; ");
    throw new Error(`Generated assessment failed validation: ${errorMsg}`);
  }

  // Filter duplicate questions based on question text content
  const uniqueQuestions = [];
  const seenTexts = new Set();

  for (const q of result.data.questions) {
    const normalizedText = q.question.toLowerCase().replace(/\s+/g, "");
    if (!seenTexts.has(normalizedText)) {
      seenTexts.add(normalizedText);
      uniqueQuestions.push({
        ...q,
        id: uniqueQuestions.length + 1, // Reset serial id
      });
    }
  }

  return {
    ...result.data,
    questions: uniqueQuestions,
  };
};

export default { validateGeneratedAssessment };
